import React from "react";
import { Inter } from "next/font/google";
import "./globals.css";
import MainNavigation from "@/components/navigation/main-navigation";
import Footer from "@/components/navigation/footer";
import { ToastContainer } from "react-toastify";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Luxury",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} relative bg-[#f5f6f8]`}>
        <ToastContainer position="bottom-right" />
        <div>
          <MainNavigation />
        </div>
        <div className="pt-24">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
